services:
  - type: web
    name: ai-accountability-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
